### ISSUE TITLE
iOS export no longer builds in Godot 4.6

### ISSUE THREAD

**Issue by pykaso** [godot-x/revenuecat#8]
**Describe the bug**
After upgrading Godot from 4.5 → 4.6 and updating the godot-x/revenuecat plugin to the latest version, the iOS export no longer builds. The Xcode build fails at the link step with missing Godot core symbols referenced from the plugin’s static library.

```
Undefined symbols for architecture arm64:
  "Object::_add_class_to_classdb(StringName const&, StringName const&)", referenced from:
      GodotxRevenueCat::initialize_class() in libGodotxRevenueCat.a[2](godotx_revenuecat.o)
  "Object::assign_class_name_static(Span<char> const&, StringName&)", referenced from:
      GodotxRevenueCat::get_class_static() (.cold.2) in libGodotxRevenueCat.a[2](godotx_revenuecat.o)
      Object::get_class_static() (.cold.2) in libGodotxRevenueCat.a[2](godotx_revenuecat.o)
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

```

**To Reproduce**
Install/update godot-x/revenuecat plugin.
Enable the plugin for iOS export.

**Expected behavior**
The iOS project should compile and link successfully (plugin loads and works at runtime).

**System (please complete the following information):**
- OS: macOS
- Target: iOS (arm64)

**Comment by paulocoutinhox** [comment]
Hi,

This is a common problem on Godot, because it don't delete the "ios/plugins/revenue_cat" folder. To resolve you need delete the folder "ios/plugins/revenue_cat" and install:

<img width="365" height="203" alt="Image" src="https://github.com/user-attachments/assets/1e53332a-c56d-470a-923e-c2558802e58e" />

Can you do it and post here the results?

**Comment by pykaso** [comment]
Thanks. Now it works!

**Comment by paulocoutinhox** [comment]
💙💙 **Support the Project** 🚀🚀

If this plugin has been helpful to you and your projects, please consider supporting its development with a donation on GitHub 🙏

Your support helps keep the project alive, maintained, and continuously improved — from bug fixes 🐛 to new features ✨ and better documentation 📘.

Every contribution, no matter the size, makes a big difference 💪💪
Thank you for being part of the community and for supporting open source ❤️❤️

👉 Donate here: [ko-fi.com/paulocoutinho](https://ko-fi.com/paulocoutinho)

🚀 Together, we can make this plugin even better!
